/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WinlossRouteImport } from './routes/winloss'
import { Route as VolumeRouteImport } from './routes/volume'
import { Route as SubmissionsRouteImport } from './routes/submissions'
import { Route as SentimentRouteImport } from './routes/sentiment'
import { Route as ScoresRouteImport } from './routes/scores'
import { Route as RawRouteImport } from './routes/raw'
import { Route as PriorityRouteImport } from './routes/priority'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NpsRouteImport } from './routes/nps'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChurnRouteImport } from './routes/churn'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSubmitTypeRouteImport } from './routes/api.submit.$type'
import { Route as ApiFormsTypeRouteImport } from './routes/api.forms.$type'

const WinlossRoute = WinlossRouteImport.update({
  id: '/winloss',
  path: '/winloss',
  getParentRoute: () => rootRouteImport,
} as any)
const VolumeRoute = VolumeRouteImport.update({
  id: '/volume',
  path: '/volume',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsRoute = SubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const SentimentRoute = SentimentRouteImport.update({
  id: '/sentiment',
  path: '/sentiment',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresRoute = ScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const RawRoute = RawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => rootRouteImport,
} as any)
const PriorityRoute = PriorityRouteImport.update({
  id: '/priority',
  path: '/priority',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NpsRoute = NpsRouteImport.update({
  id: '/nps',
  path: '/nps',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChurnRoute = ChurnRouteImport.update({
  id: '/churn',
  path: '/churn',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitTypeRoute = ApiSubmitTypeRouteImport.update({
  id: '/api/submit/$type',
  path: '/api/submit/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormsTypeRoute = ApiFormsTypeRouteImport.update({
  id: '/api/forms/$type',
  path: '/api/forms/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/churn': typeof ChurnRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/insights': typeof InsightsRoute
  '/nps': typeof NpsRoute
  '/pricing': typeof PricingRoute
  '/priority': typeof PriorityRoute
  '/raw': typeof RawRoute
  '/scores': typeof ScoresRoute
  '/sentiment': typeof SentimentRoute
  '/submissions': typeof SubmissionsRoute
  '/volume': typeof VolumeRoute
  '/winloss': typeof WinlossRoute
  '/api/forms/$type': typeof ApiFormsTypeRoute
  '/api/submit/$type': typeof ApiSubmitTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/churn': typeof ChurnRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/insights': typeof InsightsRoute
  '/nps': typeof NpsRoute
  '/pricing': typeof PricingRoute
  '/priority': typeof PriorityRoute
  '/raw': typeof RawRoute
  '/scores': typeof ScoresRoute
  '/sentiment': typeof SentimentRoute
  '/submissions': typeof SubmissionsRoute
  '/volume': typeof VolumeRoute
  '/winloss': typeof WinlossRoute
  '/api/forms/$type': typeof ApiFormsTypeRoute
  '/api/submit/$type': typeof ApiSubmitTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/churn': typeof ChurnRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/insights': typeof InsightsRoute
  '/nps': typeof NpsRoute
  '/pricing': typeof PricingRoute
  '/priority': typeof PriorityRoute
  '/raw': typeof RawRoute
  '/scores': typeof ScoresRoute
  '/sentiment': typeof SentimentRoute
  '/submissions': typeof SubmissionsRoute
  '/volume': typeof VolumeRoute
  '/winloss': typeof WinlossRoute
  '/api/forms/$type': typeof ApiFormsTypeRoute
  '/api/submit/$type': typeof ApiSubmitTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/churn'
    | '/dashboard'
    | '/docs'
    | '/insights'
    | '/nps'
    | '/pricing'
    | '/priority'
    | '/raw'
    | '/scores'
    | '/sentiment'
    | '/submissions'
    | '/volume'
    | '/winloss'
    | '/api/forms/$type'
    | '/api/submit/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/churn'
    | '/dashboard'
    | '/docs'
    | '/insights'
    | '/nps'
    | '/pricing'
    | '/priority'
    | '/raw'
    | '/scores'
    | '/sentiment'
    | '/submissions'
    | '/volume'
    | '/winloss'
    | '/api/forms/$type'
    | '/api/submit/$type'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/churn'
    | '/dashboard'
    | '/docs'
    | '/insights'
    | '/nps'
    | '/pricing'
    | '/priority'
    | '/raw'
    | '/scores'
    | '/sentiment'
    | '/submissions'
    | '/volume'
    | '/winloss'
    | '/api/forms/$type'
    | '/api/submit/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  ChurnRoute: typeof ChurnRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  InsightsRoute: typeof InsightsRoute
  NpsRoute: typeof NpsRoute
  PricingRoute: typeof PricingRoute
  PriorityRoute: typeof PriorityRoute
  RawRoute: typeof RawRoute
  ScoresRoute: typeof ScoresRoute
  SentimentRoute: typeof SentimentRoute
  SubmissionsRoute: typeof SubmissionsRoute
  VolumeRoute: typeof VolumeRoute
  WinlossRoute: typeof WinlossRoute
  ApiFormsTypeRoute: typeof ApiFormsTypeRoute
  ApiSubmitTypeRoute: typeof ApiSubmitTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/winloss': {
      id: '/winloss'
      path: '/winloss'
      fullPath: '/winloss'
      preLoaderRoute: typeof WinlossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volume': {
      id: '/volume'
      path: '/volume'
      fullPath: '/volume'
      preLoaderRoute: typeof VolumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions': {
      id: '/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentiment': {
      id: '/sentiment'
      path: '/sentiment'
      fullPath: '/sentiment'
      preLoaderRoute: typeof SentimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores': {
      id: '/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof ScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw': {
      id: '/raw'
      path: '/raw'
      fullPath: '/raw'
      preLoaderRoute: typeof RawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priority': {
      id: '/priority'
      path: '/priority'
      fullPath: '/priority'
      preLoaderRoute: typeof PriorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nps': {
      id: '/nps'
      path: '/nps'
      fullPath: '/nps'
      preLoaderRoute: typeof NpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/churn': {
      id: '/churn'
      path: '/churn'
      fullPath: '/churn'
      preLoaderRoute: typeof ChurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit/$type': {
      id: '/api/submit/$type'
      path: '/api/submit/$type'
      fullPath: '/api/submit/$type'
      preLoaderRoute: typeof ApiSubmitTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forms/$type': {
      id: '/api/forms/$type'
      path: '/api/forms/$type'
      fullPath: '/api/forms/$type'
      preLoaderRoute: typeof ApiFormsTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  ChurnRoute: ChurnRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  InsightsRoute: InsightsRoute,
  NpsRoute: NpsRoute,
  PricingRoute: PricingRoute,
  PriorityRoute: PriorityRoute,
  RawRoute: RawRoute,
  ScoresRoute: ScoresRoute,
  SentimentRoute: SentimentRoute,
  SubmissionsRoute: SubmissionsRoute,
  VolumeRoute: VolumeRoute,
  WinlossRoute: WinlossRoute,
  ApiFormsTypeRoute: ApiFormsTypeRoute,
  ApiSubmitTypeRoute: ApiSubmitTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
